version: '3.8'

services:
  # --- BANCO DE DADOS (MYSQL) ---
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerencia_produtos_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dev_user", "-pdev_password"]
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app-network

  # --- BACKEND (SPRING BOOT) ---
  backend:
    build:
      context: ./back_end_gerencia_produtos
      dockerfile: Dockerfile
    container_name: products_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gerencia_produtos_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # --- FRONTEND (ANGULAR) ---
  frontend:
    build:
      context: ./front_end_gerencia_produtos
      dockerfile: Dockerfile
    container_name: products_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge